name = "machine-decides-vote"
compatibility_date = "2026-06-18"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "machine-decides-vote"
database_id = "58369438-ac38-447a-8194-8d6564c467e3"
